server/__init__.py
"""Package and module dependency imports."""
from flask import Flask
from flask_cors import CORS
from flask_pymongo import PyMongo
from server.config import Config

app = Flask(__name__)

app.config.from_object(Config)  # For environment setup

mongo = PyMongo(app)  # For database setup
db = mongo.db

CORS(app)  # To enable cross origin access from client to server

# Import blueprinted routes and register blueprints
# Blueprints may be a bit unecessary for the size of my API, but,
# I like the format

from server.main.routes import main

app.register_blueprint(main)

server/main/routes.py
"""Package and module dependency imports."""
from flask import Blueprint, request, jsonify, render_template
from server import db
from bson.json_util import dumps
from server.main.data import generate_text

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    """Show the user the homepage."""
    return render_template("brain.html")


@main.route("/kerasgenerator", methods=['GET', 'POST'])
def kerasgenerator():
    """Generate text based on keras model and user input."""
    if request.method == "POST":
        user_input = request.form.get('user-input')
        response = generate_text(user_input)
        context = {
            "response": response,
            "user_input": user_input
        }
        return render_template('generator.html', **context)
    return render_template('generator.html')


@main.route("/about")
def about():
    """Render about.html."""
    return render_template("about.html")


@main.route("/gettrainingdata")
def show_training_data():
    """Return all training data as json to client."""
    training_data = db.trainingdata.find({})
    return dumps(training_data)

server/templates/about.html
{% extends "base.html" %}
{% block content %}

<body>
  <h2>About the Burroughs-Generator</h2>
  <div class="main-content">

    <div class="main-content-inner">

      <h4>So, what is it?</h4>
      <p>
        Artificial neural networks are machine learning systems that learn much
        in the same way as humans or other mammals. Through training, they learn
        to achieve goals in different ways by making mistakes, calculating their
        error, and then attempting the problem again.
      </p>
      <p>
        Much like how all of us at one point in time figured out how to throw or kick a ball into
        a goal or to another person, the neural net takes a shot at a problem or goal, and uses what is called "backpropagation" to
        determine its misses. It then uses something called "forward propogation" to try again, having
        adjusted its approach to the problem, the same way you would decide how much energy to put into a second
        throw after missing the goal by a few feet the first time.
      </p>
      <img src="{{ url_for('static', filename='assets/neural_network_diag.png')}}" alt="A diagram of a generic neural network">
    </div>
  </div>
  <p>
    While this neural net was trained on text input, our computers don't really understand this. They understand numbers.
    This means that the Burroughs-Generator isn't able to take grammatical or spelling feedback in the same way we can. Instead, the input
    it was given was turned into numbers, and it uses a series of mathematical functions to assign weights to these. Based on its performance,
    it is able to re-assign these weight values in order to learn from its mistakes. The diagram above shows the general architechture of a neural net
    with one input neuron, one output neuron, and three hidden layers: two with three neurons and one with two neurons.
    As the input values are passed through these hidden layers, the net is performing mathematical calculations to detmine the output based
    on the weights of the data.
  </p>
  <div class="highlight-content">
    <div class="highlight-content-inner">
      <p>
        You may have heard of AI, machine learning, or neural networks before. These computing systems are being deeply explored because of their
        massive potential to revolutionize nearly everything: medicine, service industries, tech, defense,
        education, and many more. Machines being able to learn like humans may seem scary, but as you may have realized with the Burroughs-Generator,
        computers still have a long way to go before they can truly do all of the general tasks humans can. Emulating other humans is easy for us
        , but it took the V 2.0 network over 100,000 characters and hours of training to even begin to make sense.
      </p>
      <p>
        Still, neural networks are robust and flexible systems that can solve complex problems very effectively. They can make
        many tasks much easier, like deciding which combinations of chemicals are most likely to make an effective medicine, predicting what
        you're going to type next or what you meant to type when you make a spelling mistake. They're also great at making more complex predictions,
        like what content on Instagram will keep you online and engaged, or what Amazon products to recommend next time you log in!
      </p>
    </div>
  </div>
  <a href="https://brain.js.org/#/" class="follow-link">You can learn more about Brain.js here</a>
  <a href="https://en.wikipedia.org/wiki/Keras"class="follow-link">You can learn more about Keras here</a>
  <a href="https://en.wikipedia.org/wiki/Artificial_neural_network"class="follow-link">Check out this Wikipedia article for more information on neural networks.</a>
</body>
{% endblock %}

server/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <!-- to fix favicon.ico 404 error in localenv -->
  <link rel="shortcut icon" href="">
  <!-- scripts & stylesheets -->
  <script src="//unpkg.com/brain.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}" defer></script>
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>Burroughs-Generator</title>
  </link>
  {% block head %}{% endblock %}
</head>

<body>
  <header>
    <h5>
      “The study of thinking machines teaches us more about the brain than we can learn by introspective methods.
      Western man is externalizing himself in the form of gadgets.”
    </h5>
    <button class="nav" id="hamburger-menu"><img src="{{ url_for('static', filename='assets/menu-2.svg') }}" alt="hamburger menu"></button>
    <nav class="invisible nav" id="side-nav">
      <a href="{{ url_for('main.about') }}">About the Generator</a>
      <a href="{{ url_for('main.home') }}">v 1.0</a>
      <a href="{{ url_for('main.kerasgenerator') }}">v 2.0</a>
    </nav>
  </header>
  {% block content %}{% endblock %}
</body>

<footer>Copyright © Sid Arcidiacono 2020</footer>

</html>

server/templates/brain.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript" src="{{ url_for('static', filename='net.js') }}" defer></script>
{% endblock %}

{% block content %}

<body>
  <h1>Talk to William Burroughs</h1>


  <div class="main-content">
    <div class="main-content-inner">
      <h4>Version 1.0 powered by Brain.js</h4>
      <h5>
        Brain.js is an accelerated neural net built for JavaScript and Node.js.
        This means this one is running in the browser itself. Go to "Develop" and "Open JavaScript Console".
        Then, input some text and watch it train!
        Don't leave right away! - this net takes between 2 and 4 minutes to provide a response.
      </h5>
      <p>Go to the menu in the upper right to check out Version 2.0, and see the difference.</p>
      <h2>Say Something:</h2>

      <section>
        <img src="{{ url_for('static', filename='assets/icons8-cockroach-100.png')}}" alt="cockroach loading animation" class="invisible" id="load-cockroach">
        <p class="invisible" id="user-input">User Input</p>
        <h4 class="invisible" id="response">Response</h4>
        <input type="text" name="question" id="question">
        <button id="submit-question">Send</button>
        <button class="invisible" id="say-more">Say More</button>

      </section>
    </div>
  </div>
</body>
{% endblock %}

server/templates/generator.html
{% extends "base.html" %}

{% block content %}

<body>

  <h1>Talk to William Burroughs</h1>
  <div class="main-content">
    <div class="main-content-inner">
      <h4>Version 2.0 powered by Tensorflow & Keras</h4>
      <h5>
        Keras is a deep learning library built on Tensorflow, and this model was built
        specifically to generate text character by character.
        Don't leave just yet! This net takes between 45 seconds and 3 minutes to provide a response.
      </h5>
      <p>Can you tell the difference?</p>

      <h2>Say Something:</h2>

      <section>

        {% if response %}
        <p>{{ user_input }}</p>
        <h4 id="response">{{ response }}</h4>
        <p>
          Burroughs-Generator's English skills could still use some work, but we're getting there!
          With more computational power and data, there's the potential for
          much more coherent and adept responses, like your phone's voice assistant.
        </p>
        <form class="" action="{{ url_for('main.kerasgenerator')}}" method="GET">
          <input type="submit" name="say-more" value="Say More">
        </form>
        {% else %}
        <img src="{{ url_for('static', filename='assets/icons8-cockroach-100.png') }}" alt="Cockroach outline loading icon" class="invisible" id="cockroach">
        <form class="user-comment" action="{{ url_for('main.kerasgenerator') }}" method="POST">
          <input type="text" name="user-input">
          <input type="submit" value="Send" id="submit-btn">
        </form>
        {% endif %}
      </section>
    </div>
  </div>

</body>

{% endblock %}

server/templates/index.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript" src="{{ url_for('static', filename='index.js') }}" defer></script>
<script type="text/javascript" src="{{ url_for('static', filename='net.js') }}" defer></script>
{% endblock %}

{% block content %}
  <body>
    <h4>
      “The study of thinking machines teaches us more about the brain than we can learn by introspective methods.
      Western man is externalizing himself in the form of gadgets.”
    </h4>
    <h1>Talk to William Burroughs</h1>

  <section>
    <div>
          <h2>Ask a Question, or Make a Comment:</h2>
    </div>
  </section>

  <section>
    <div>
      <p class="invisible" id="user-input">User Input</p>
      <h4 class="invisible" id="response">Response</h4>
        <input type="text" name="question" id="question">
        <button id="submit-question">Send</button>
        <button class="invisible" id="say-more">Say More</button>
    </div>
   </section>

  </body>
{% endblock %}